version: '3.9'

services:
  master:
    image: locustio/locust:2.20.0
    container_name: locust-master
    ports:
      - "8089:8089"
    volumes:
      - ./src:/mnt/locust 
    working_dir: /mnt/locust
    command: -f /mnt/locust/locustfile.py --master
    networks:
      - loadtest-net

  worker:
    image: locustio/locust:2.20.0
    volumes:
      - ./src:/mnt/locust
    working_dir: /mnt/locust
    command: -f /mnt/locust/locustfile.py --worker --master-host=master
    depends_on:
      - master
    deploy:
      replicas: 3
    networks:
      - loadtest-net

  target:
    build: ./target_app
    container_name: mock-backend
    ports:
      - "8000:8000"
    networks:
      - loadtest-net

networks:
  loadtest-net:
    driver: bridge

